name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Login to GitHub Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Stop any old version
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            
            # Pull the EXACT image built in the previous step
            docker pull ghcr.io/ibrarli/apextechhub-website:latest
            
            # Run it
            docker run -d --name nextjs-app -p 3000:3000 ghcr.io/ibrarli/apextechhub-website:latest